### ISSUE TITLE
Disable flag is not working 

### ISSUE THREAD

**Issue by manishmani2004** [DHD2280/Oxygen-Customizer#13]
### Describe the bug

I turned off all disable flag models in magisk but idk but it still shows Package not responding 
![Screenshot_2024-05-13-22-30-04-10_cdb399bbdd5ae3a3da2a11647bc61a18](https://github.com/DHD2280/Oxygen-Customizer/assets/148568686/27e11a68-eb75-47d2-acb7-a6665b399cd0)

### Expected behavior

Wanted to take screenshots in WhatsApp,Paytm etc

### Screenshots

![Screenshot_2024-05-13-22-30-04-10_cdb399bbdd5ae3a3da2a11647bc61a18](https://github.com/DHD2280/Oxygen-Customizer/assets/148568686/71dc2397-1c34-4079-b491-ecd9eaeda7cf)

### Device information

- Device: [e.g. OnePlus 9rt]
- OS: [e.g. Oxygen OS 14 with update 14.0.0.600]
- App version: [e.g. v1.0.0]

**Comment by DHD2280** [comment]
Are you sure that the feature doesn't work?
Or are you worried about 'Package not responding'?
Tap on info to see the explanation.
Try to make a screenshot in a restricted app and check if it works.

**Comment by manishmani2004** [comment]
> Are you sure that the feature doesn't work?
> Or are you worried about 'Package not responding'?
> Tap on info to see the explanation.
> Try to make a screenshot in a restricted app and check if it works.

Yep it's not working checked right now "can't take a ss due to pp restrictions" tried in whstapp, Paytm. On custom rom it was working fine 😕

**Comment by DHD2280** [comment]
Which version of LSposed?

**Comment by manishmani2004** [comment]
> Which version of LSposed?

V1.9.2 (7024) 
Shell -version 14

**Comment by MOO-3MAD** [comment]
![Screenshot_2024-05-25-10-38-14-08_cdb399bbdd5ae3a3da2a11647bc61a18.jpg](https://github.com/DHD2280/Oxygen-Customizer/assets/44984837/bec07927-4e81-4475-b78a-132a6d03ad26)

I have this bug too, if u can solve it do this please

**Comment by DHD2280** [comment]
This is not a bug, read the explanation by clicking info in the menu.
Maybe the app is not open.

Anyway I was a little busy.
Clean lsposed logs.
Ensure that disable flag is ON.
Reboot your phone.
Send LSposed logs after the boot is completed so I can check.
Thank you

**Comment by MOO-3MAD** [comment]
![LSPosed_2024-05-25T10_49_20.108146.zip](https://github.com/DHD2280/Oxygen-Customizer/files/15442183/LSPosed_2024-05-25T10_49_20.108146.zip)

Those are the logs after reboot.

**Comment by Mohamedemad0122141** [comment]
![LSPosed_2024-05-25T10_49_20.108146.zip](https://github.com/DHD2280/Oxygen-Customizer/files/15442182/LSPosed_2024-05-25T10_49_20.108146.zip)

**Comment by DHD2280** [comment]
Hello, can you try the latest nightly build from GH Actions?
