### ISSUE TITLE
[BUG] Duplicate entries in search when trying to update in app

### ISSUE THREAD

**Issue by sigmazhou** [DHD2280/Oxygen-Customizer#16]
### Describe the bug

Trying to update in app will fail to install and create duplicate entries in search. See below for screenshot.
This might also be a bug that updating in app not working when current installation is with APK from Telegram (Though the apk from Telegram looks the same as from the updater in app, not sure what's the problem here).

Clearing app data fixed the issue.

### Steps to reproduce

1. Install beta-9 (apk from Telegram), don't need to restart phone.
2. Make a search (maybe not necessary) 
3. Check for update in app, download update and click notification to install
4. Get "App not installed as package conflicts with an existing package" error
5. Try search for the same term again
6. Repeating step 3-5 will create 3rd duplicate entry.

### Expected behavior

Only single entry in search.

### Screenshots

![image](https://github.com/DHD2280/Oxygen-Customizer/assets/30397196/ed04b477-e6c4-4767-aa81-505ebd2bef3d)

### Device information

- Device: Oneplus 12 US variant CPH2583
- OS: OxygenOS 14 CPH2583_14.0.0.610(EX01)
- Root: Magisk 27.0 (27000), LSPosed 1.9.2 (7024)
- App version: beta-9 from Telegram

**Comment by DHD2280** [comment]
Hello, please try latest nightly from [GitHub actions](https://github.com/DHD2280/Oxygen-Customizer/actions)

**Comment by sigmazhou** [comment]
> Hello, please try latest nightly from [GitHub actions](https://github.com/DHD2280/Oxygen-Customizer/actions)

(The following is for beta-10, let me try latest nightly)
Hi, since latest don't have "update" option (there's no newer version) I can reproduce the bug with switch branch to stable.
In this case the error message when installing update becomes "App not installed as package appears to be invalid"

**Comment by sigmazhou** [comment]
> Hello, please try latest nightly from [GitHub actions](https://github.com/DHD2280/Oxygen-Customizer/actions)

This looks like fixed in the latest nightly. Thanks!
