### ISSUE TITLE
Weather appears on the clock in lock sreen[BUG] Your title here

### ISSUE THREAD

**Issue by MOO-3MAD** [DHD2280/Oxygen-Customizer#17]
### Describe the bug

Weather appears on the clock in lock sreen

### Expected behavior

Nothing

### Screenshots

![Screenshot_2024-05-22-05-22-40-74](https://github.com/DHD2280/Oxygen-Customizer/assets/44984837/f5b277de-aa86-4a17-b3a9-b25bb2f82b5c)

### Device information

- Device: [e.g. OnePlus 10 Pro]
- OS: [e.g. Oxygen OS 14 with update 14.0.0.700]
- App version: [Beta 10]

**Comment by DHD2280** [comment]
Adjust clock bottom margin.

**Comment by MOO-3MAD** [comment]
> Adjust clock bottom margin.

This made the notifications start from the bottom of the screen.
If u can delete the battery percentage from this clock and add the weather it will be awesome.

**Comment by DHD2280** [comment]
> This made the notifications start from the bottom of the screen.

Adjust weather top margin.

> If u can delete the battery percentage from this clock and add the weather it will be awesome.

Unfortunately this isn't possible, since I want to keep the two features separated.
So anyone can use lockscreen or weather separately and both together.

**Comment by MOO-3MAD** [comment]
Can u make the weather margins fully manageable soci can put it at the bottom of the screen without affecting the notification place.
