### ISSUE TITLE
Brightness Slider Color (and) Notification scrim bug

### ISSUE THREAD

**Issue by SGtriangle** [DHD2280/Oxygen-Customizer#18]
### Describe the bug

**Brightness Slider Colors and Notification Scrim Colors not working on COS 13 or OOS 13**

### Device information

- Device: [Realme 8]
- OS: [COS 13]
- App version: [Latest Beta Builds]

**Comment by DHD2280** [comment]
Hello.

Do you mean notification transparency?

Notification transparency has been reported not working in COS, maybe in COS it is different.

For brightness slider color and notification transparency I can confirm that in OOS13 both features are working fine.
