### ISSUE TITLE
Album art on lockscreen

### ISSUE THREAD

**Issue by Mblues84** [DHD2280/Oxygen-Customizer#19]
### Describe the feature

Thank you for your great job 
Is it possible to add the album art of the music playing on the lockscreen 

### Why would it be useful to add?

It's pretty beautiful to be seen on the lockscreen 

### Example(s)

![images](https://github.com/DHD2280/Oxygen-Customizer/assets/35265945/2b807584-2002-4e95-942f-412db60b6410)

**Comment by DHD2280** [comment]
Available on latest nightly and soon in the next beta release!
