### ISSUE TITLE
[FEATURE] Resizing AOD and add weather

### ISSUE THREAD

**Issue by vegetaleb** [DHD2280/Oxygen-Customizer#21]
### Describe the feature

I am very happy to see yo uare planning to add AOD customisation.
As I found the stock AOD pretty but too small I hope you will give us the possibility to enlarge them
Also please add weather option like with Pixel's AOD

### Why would it be useful to add?

To make out Oneplus 12 even better than ever

### Example(s)

![1414762610670174208](https://github.com/DHD2280/Oxygen-Customizer/assets/156313252/c0d9114e-23c1-4785-8d17-00ca58d40365)

**Comment by DHD2280** [comment]
Hello.
Currently AOD Custom Clock feature is in beta test.
If you would like to test, you can join the support group or you can try nightly builds in GitHub actions.
The weather in AOD is in great demand, maybe I will add too.

**Comment by vegetaleb** [comment]
> Hello. Currently AOD Custom Clock feature is in beta test. If you would like to test, you can join the support group or you can try nightly builds in GitHub actions. The weather in AOD is in great demand, maybe I will add too.

Thanks
How can I join the beta testers group?

**Comment by DHD2280** [comment]
There is the link on the main page of the repository.
