### ISSUE TITLE
[BUG] ControlUI crash/restart (and possibly other components also) with font size change of Statusbar Clock

### ISSUE THREAD

**Issue by ChillDuder** [DHD2280/Oxygen-Customizer#34]
### Describe the bug

I'm using dev#325 (but also had this on #318 i think)
On a oneplus 12 recently updated to OxygenOS-CPH2581_14.0.0.810 (global). Few days before i started to used the option to change the fontsize of statusbar clock. (So i'm not sure if oos customizer or latest rom version is the cause, or both ;-P)

While screen off, and try to turn it on, it stays black. Nothing to do for about 10 seconds. With long power button click then this android emerceny power menu come up (black background still) where you can reboot and other, also 'build crashlog'. which i choose (attachements here). again after about 20 second lockscreen will come up and the phone continue to work fine without a reboot.
I got this oos crashlogs and luckily a crash catched by LogFox (log app) which shows that the SCREEN_ON broadcast catched by oxygen customizer lsposed module caused the crash. (file with crash.. prefix)
This is not a usual controlUI crash/restart only (i modded a lot last years) because of the behaviour with black screen etc.

With fontsize changed i get this one or two times a day. really random. Now i only statusbar battery level fontsize changed (which i already used for a long time) to see if this happens again with latest oos.

Thank you very much 

Attachments:
[bugreport-CPH2581-UKQ1.230924.001-2024-07-12-18-58-28.zip](https://github.com/user-attachments/files/16199677/bugreport-CPH2581-UKQ1.230924.001-2024-07-12-18-58-28.zip)
[bugreport-CPH2581-UKQ1.230924.001-2024-07-11-20-44-01.zip](https://github.com/user-attachments/files/16199678/bugreport-CPH2581-UKQ1.230924.001-2024-07-11-20-44-01.zip)

[crash-com-android-systemui-12_07-18-58-39_995.zip](https://github.com/user-attachments/files/16199685/crash-com-android-systemui-12_07-18-58-39_995.zip)

### Steps to reproduce

No way. too random. No method to reproduces found until now.

### Expected behavior

No crash with statusbar fontsize clock changed.

### Device information

- Device: oneplus 12
- OS: Oxygen OS 14 with update 14.0.0.810 global]
- App version: dev #316-325

**Comment by DHD2280** [comment]
Hello,
Thank you for reporting.
Do you have LS Weather Enabled?
Last June Security Patch update broke a lot of things.
Will check and let you know

Also, can you try nightly #330?

**Comment by ChillDuder** [comment]
so:

i run the #316 without fontsize statusbar clock changed (returned to default) for almost 24 hours: no crash again (i know, thats not that much time, but anyway)
then in installed your last #332 and changed fontsize: about after half an hour i had the crash again, turning on the screen with power button (but this is not reproducing it always). same crashlog.
Now i run without fontsize change of statusbar clock for 6 hours without a crash. will report, if it crashed without fontsize change.

LS weather is enabled for a long time. never had issues because of that, i think.

Attachment with all my current settings. 
I also have luckytool installed but with only few mod enabled and no one of the statusbar mods.

[OxygenCustomizer_Config.bin.zip](https://github.com/user-attachments/files/16203790/OxygenCustomizer_Config.bin.zip)

edit: can this be connected to having a LS carrier text replacement set?

**Comment by DHD2280** [comment]
Seems that the problem was related to Weather, since I was changing some stuff in Weather Task.
Can you try latest #337?

Thank you

**Comment by ChillDuder** [comment]
Hi, 
thank you very much.

I'm using #338 for almost a day now with LS weather and statusbar clock fontsize change on. No crash until now.
Look's fine.

Please leave this open for a few days. If a crash happens again, i will report here.

Thanks for your great mod-collection tool.

**Comment by DHD2280** [comment]
Thank you for you reports.

Fixed with [cfd7dcf](https://github.com/DHD2280/Oxygen-Customizer/commit/cfd7dcfc6edaa41baeb07beacd9b458df6764c91) commit.
