### ISSUE TITLE
[FEATURE] Fullscreen caller id

### ISSUE THREAD

**Issue by Mblues84** [DHD2280/Oxygen-Customizer#50]
### Describe the feature

is it possible to make a fullscreen caller id picture in com.android.incallui

### Why would it be useful to add?

That's will be cool to see

### Example(s)

![images](https://github.com/user-attachments/assets/a3ad9fb2-4aba-4eb5-ac23-d18d2c830884)

**Comment by DHD2280** [comment]
This UI is handled by your Dialer app.
