### ISSUE TITLE
Allow Users to Customize Depth Wallpaper

### ISSUE THREAD

**Issue by Ziyuan-Sun** [DHD2280/Oxygen-Customizer#57]
### Describe the feature

Allow users to choose foreground.jpg & background.jpg, but not have to use AI model.

### Why would it be useful to add?

In some areas like China, because of policy, AI model cannot be provided by Google.

### Example(s)

just like _Iconify_

**Comment by DHD2280** [comment]
I will add this feature, with the ability to choose depth with a custom image or AI.

**Comment by Ziyuan-Sun** [comment]
> I will add this feature, with the ability to choose depth with a custom image or AI.

Thank u so much for your reply! Looking forward to meeting the new version.🤓

**Comment by DHD2280** [comment]
Please try the build and let me know :)

**Comment by Ziyuan-Sun** [comment]
> Please try the build and let me know :)

It seems not to work.😢![Screenshot_2024-09-14-18-23-58-72_cdb399bbdd5ae3a3da2a11647bc61a18.jpg](https://github.com/user-attachments/assets/2249a8a3-dc8f-4867-a008-c708cbbcc151)

![Screenshot_2024-09-14-18-23-47-86.jpg](https://github.com/user-attachments/assets/44af13bd-e767-4c41-a35b-35c0704a7176)

**Comment by DHD2280** [comment]
Can you check if in the folder .oxygen_customizer/ there are the two files?
Should be the background and the subject.
Also, have you tried to restart SystemUI?

**Comment by Ziyuan-Sun** [comment]
> Can you check if in the folder .oxygen_customizer/ there are the two files?
> Should be the background and the subject.
> Also, have you tried to restart SystemUI?

There is, and I have restarted SystemUI.![Screenshot_2024-09-14-19-04-00-54_9e8df3d0c7c1f50248b6ee043a653d26.jpg](https://github.com/user-attachments/assets/84f8060a-6eb0-40da-b023-eb8d29b23a71)

**Comment by DHD2280** [comment]
![Screenshot_2024-09-14-13-41-55-48.jpg](https://github.com/user-attachments/assets/e631a9a5-6b76-434a-a481-0e8d0dede9fb)

Can you provide lsposed logs?

**Comment by Ziyuan-Sun** [comment]
> ![Screenshot_2024-09-14-13-41-55-48.jpg](https://github.com/user-attachments/assets/e631a9a5-6b76-434a-a481-0e8d0dede9fb)
> 
> Can you provide lsposed logs?

![LSPosed_2024-09-14T21_11_12.711392.zip](https://github.com/user-attachments/files/17002528/LSPosed_2024-09-14T21_11_12.711392.zip)

**Comment by DHD2280** [comment]
Please try again with latest official LSposed instead of mod

**Comment by Ziyuan-Sun** [comment]
> Please try again with latest official LSposed instead of mod

Thank u very much, I do so and it works. But there is one final problem: the size and aspect ratio of the overlay wallpaper differs from that of the system's wallpaper, which results in a noticeable visual change during the brief moment of unlocking. (The system will automatically crop the edges of the wallpaper. I have temporarily resolved this problem by cropping the image.)

**Comment by DHD2280** [comment]
> 
> Thank u very much, I do so and it works. But there is one final problem: the size and aspect ratio of the overlay wallpaper differs from that of the system's wallpaper, which results in a noticeable visual change during the brief moment of unlocking. (The system will automatically crop the edges of the wallpaper. I have temporarily resolved this problem by cropping the image.)

Unfortunately I can't do anything about this, you have to set background and foreground matching your display size.
It's why I prefer AI, because it took the background directly from the system and creates the subject.
Thank you for your reports 👍

**Comment by Ziyuan-Sun** [comment]
> > 
> > Thank u very much, I do so and it works. But there is one final problem: the size and aspect ratio of the overlay wallpaper differs from that of the system's wallpaper, which results in a noticeable visual change during the brief moment of unlocking. (The system will automatically crop the edges of the wallpaper. I have temporarily resolved this problem by cropping the image.)
> 
> Unfortunately I can't do anything about this, you have to set background and foreground matching your display size.
> It's why I prefer AI, because it took the background directly from the system and creates the subject.
> Thank you for your reports 👍 

Similarly, appreciate your efforts.🥰
