### ISSUE TITLE
Request iOS 16 style battery icon

### ISSUE THREAD

**Issue by Jacky5863** [DHD2280/Oxygen-Customizer#59]
Can you provide an APK for the iOS 16 style battery icon? As it is a realme model with a module bug, I just want this battery icon. If you could help make this icon into a mask module, that would be great

**Comment by DHD2280** [comment]
Hello.
Users reported that the app is correctly working on RUI 4/5.
Obviously on RUI 4, as OOS13 there are some limitations.
If you want to have only that battery as a module you can use [those paths](https://github.com/DHD2280/Oxygen-Customizer/blob/da04632b90297ba4ba8dc973c18bdeb4bd14583e/app/src/main/res/values/battery_configs.xml#L194) and build your own overlay module.
