### ISSUE TITLE
[FEATURE] Disable camera button on lock screen 

### ISSUE THREAD

**Issue by anonimgall** [DHD2280/Oxygen-Customizer#64]
### Describe the feature

It would be helpful to add possibility to disable camera button from lock screen. I am using OnePlus 12 and it's kinda annoying that anyone can make pictures without unlocking the phone first.

### Why would it be useful to add?

My son takes my phone frequently and he is taking unwanted pictures.

### Example(s)

Camera button on lock screen

**Comment by DHD2280** [comment]
You can hide right affordance from Lockscreen page.
