### ISSUE TITLE
[BUG] Music visualization not working

### ISSUE THREAD

**Issue by elisenlebkuch** [DHD2280/Oxygen-Customizer#69]
### Describe the bug

The music visualization doesn't work anymore on the current version of OxygenOs 14. It simply doesn't show on lockscreen, navbar, or ambient display, no matter the settings. (I also tried it on 14.0.0.802 with the latest beta because nightly wouldn't install properly for some reason and it worked on there.)

### Steps to reproduce

1. Enable "Pulse" in " Sound" menu
2. See that it doesn't work

### Expected behavior

It should work.

### Device information

- Device: OnePlus 12
- OS: Oxygen OS 14 Global variant with update 14.0.0.840
- App version: nightly-10 (#805)

**Comment by DHD2280** [comment]
If you have spatial audio enabled, disable it.
Ensure that you are on official lsposed.
Send LSposed logs.

**Comment by elisenlebkuch** [comment]
I turned off spacial audio and switched to official LSPosed. Here are the Logs: 
[LSPosed_2024-10-08T18_12_51.557751.zip](https://github.com/user-attachments/files/17296206/LSPosed_2024-10-08T18_12_51.557751.zip)

**Comment by DHD2280** [comment]
Does this happen with every render style?
Are you on power save mode?

**Comment by elisenlebkuch** [comment]
It was power save mode. Sorry, should have thought of this, it works now as it should.

**Comment by DHD2280** [comment]
I preferred to don't show pulse in power save mode :)

**Comment by elisenlebkuch** [comment]
Btw, what does the "Fluid Music" feature do?
