### ISSUE TITLE
[FEATURE] Remove Google Feed from Launcher

### ISSUE THREAD

**Issue by momanan** [DHD2280/Oxygen-Customizer#7]
### Describe the feature

please disable the Google news feed, which opens with a gesture to the right from the left edge of the screen in OnePlus smartphones on oxygenOs
![IMG_20240503_235836](https://github.com/DHD2280/Oxygen-Customizer/assets/49413968/821c1b92-23b9-43c0-8b53-335fce7348ef)

### Why would it be useful to add?

Many users do not need this feature and it can be very annoying

### Example(s)

Many users do not need this feature and it can be very annoying
![IMG_20240503_235836](https://github.com/DHD2280/Oxygen-Customizer/assets/49413968/ce5a9040-25d5-4022-943e-9328acbe2e5f)

**Comment by DHD2280** [comment]
Hello.
Thank you for the feature request.
Will comment here when I will add.
Thank you.
