### ISSUE TITLE
[BUG]Notification Corner Radius bug？

### ISSUE THREAD

**Issue by seraph758** [DHD2280/Oxygen-Customizer#71]
### Describe the bug

![Screenshot_2024-10-13-12-04-08-04~2](https://github.com/user-attachments/assets/1137e6cf-dea5-464e-a6aa-048b7470a83e)
![Screenshot_2024-10-13-12-03-08-73_cdb399bbdd5ae3a3da2a11647bc61a18](https://github.com/user-attachments/assets/d8087bcc-131f-4b1f-a7fe-3f9b99ecd17d)

### Expected behavior

The setting is not effective

### Device information

- Device: [e.g. OnePlus 12]
- OS: [e.g. Oxygen OS 14 with update 14.0.0.850]
- App version: [beta-11]

**Comment by DHD2280** [comment]
Hello.
Please send LSposed logs.

**Comment by seraph758** [comment]
Sorry, my mistake. I set Notification Styles, so I have this problem
