### ISSUE TITLE
[BUG] Asking for reboot every launch

### ISSUE THREAD

**Issue by Marutselu** [DHD2280/Oxygen-Customizer#72]
### Describe the bug

Every launch it is like first time it initializes then asks to reboot. Even though I rebooted.
Tried with a few days old dev build and the newest beta 11.
Op12 oos 840

### Expected behavior

It shouldn't ask for reboot after rebooting and it should retain the data and the initialization

### Device information

- Device: [e.g. OnePlus 11] op12
- OS: [e.g. Oxygen OS 14 14.0.0.601] oos 14 840
- App version: [e.g. v1.0.0] beta 11
- lsposed 1.9.2
- kernelsu 11928

**Comment by DHD2280** [comment]
Some people reported that some modules can cause issues.
Try to remove (remove, not only disable) all Apatch modules.
Enable only OxygenCustomiser & lsposed (zygisk next too) and reboot.

**Comment by Marutselu** [comment]
I am using kernelsu. I don't have many modules installed, just the basic ones. 
Play integrity fix
Shamiko
Lsposed
Zygisk next
Sui
Zygisk detach
YouTube revanced
Systemless hosts

As these are all essential for using my phone. It is not possible for me to uninstall them.

**Comment by DHD2280** [comment]
Try to disable "unmount modules".
Also I was not asking to remove modules forever, just test if some of them could cause this issue.
