### ISSUE TITLE
[BUG] Battery and Network Status icons jump to left of screen when notifications expanded

### ISSUE THREAD

**Issue by mweser** [DHD2280/Oxygen-Customizer#74]
### Describe the bug

I have my clock set up to be on the far right-hand side of the screen ordinarily, with battery and network indicators to the left of it (screenshots included).

When I pull down the notifications/quick settings, the battery icon and network indicator jump to odd places on the left of the screen.

When this happens, in order to open the battery usage history activity in settings, I need to tap on the battery icon in the upper left as opposed to its usual position on the right. 

### Steps to reproduce

1. Configure settings to match my screenshots 
2. Pull down on the notifications from any screen 
3. Observe battery icon movement from one side of the screen to the other. 

### Expected behavior

Battery icon should remain on the side of the screen where they are in the status bar. 

### Screenshots

![Screenshot_2024-10-17-12-55-02-20_cdb399bbdd5ae3a3da2a11647bc61a18](https://github.com/user-attachments/assets/ecf9d0fd-d61c-4c60-b6f9-5c4e6a597e66)
![Screenshot_2024-10-17-12-54-07-82_3d88d13491c3c5d191dc1c89ab1722b7](https://github.com/user-attachments/assets/a650bd39-503c-4194-94e1-6511970b00c1)
![Screenshot_2024-10-17-12-53-38-13_3822ac0e29cfec8970059bb21d01f05e](https://github.com/user-attachments/assets/181bc0a2-8a68-4f01-9c27-f42e02267f15)
![Screenshot_2024-10-17-12-54-22-96_cdb399bbdd5ae3a3da2a11647bc61a18](https://github.com/user-attachments/assets/7c9a253d-67c8-4862-bd04-fd1f8eaf08d8)
![Screenshot_2024-10-17-12-54-34-19_cdb399bbdd5ae3a3da2a11647bc61a18](https://github.com/user-attachments/assets/82d9ce1c-6785-4546-9a91-9fa8d835aa90)
![Screenshot_2024-10-17-12-53-53-95_3822ac0e29cfec8970059bb21d01f05e](https://github.com/user-attachments/assets/d055c620-80af-458c-a1ae-8a0a9c2d09de)
![Screenshot_2024-10-17-12-53-50-74_3822ac0e29cfec8970059bb21d01f05e](https://github.com/user-attachments/assets/9428c9a4-de90-41c1-a5d9-766562717db8)
![Screenshot_2024-10-17-12-56-12-13](https://github.com/user-attachments/assets/77673d76-6b54-4ee6-b520-2d0f559b06c4)
![Screenshot_2024-10-17-12-55-18-95](https://github.com/user-attachments/assets/b0c688bf-ad56-41fc-b71f-f911b9041b47)
![Screenshot_2024-10-17-12-53-38-13_3822ac0e29cfec8970059bb21d01f05e~2](https://github.com/user-attachments/assets/c58c3c6b-0b5f-4557-b9f9-6efa6d8d1545)

### Device information

- Device: OnePlus 12
- OS: Oxygen OS 14 with update 14.0.0.604
- App version: beta-11

**Comment by DHD2280** [comment]
Hello
This layout isn't touched by Oxygen Customizer.
This you are showing in screenshot is the System Icons Area on Header.
Please try latest nightly from github actions and check again.
Also attach your lsposed logs

**Comment by mweser** [comment]
> Hello This layout isn't touched by Oxygen Customizer. This you are showing in screenshot is the System Icons Area on Header. Please try latest nightly from github actions and check again. Also attach your lsposed logs

Will do.

**Comment by DHD2280** [comment]
> Will do. 

Hello.
Any news?
Can I close the issue?
