### ISSUE TITLE
[BUG] Unable to Theme Notifications, Quick Settings Background, Status Bar Icons OP12 2583.840

### ISSUE THREAD

**Issue by nanodan52** [DHD2280/Oxygen-Customizer#75]
### Describe the bug

Hello, 
I am on OOS 2583.840 on my Oneplus 12 and I am unable to get this app to theme the items in the Bug Title.

Things that are not working: 
- Notification theming (color, style, transparency, basically no notification modification takes effect)
- Toast message theming style works, but unable to change color of the main toast message
- Quick Settings background transparency / Blur
- Status bar icons (WiFi, Signal) 

The main thing I am looking to do is make notification background black again. This worked on the last OOS version (either 830 or 810 i believe it was) but stopped working with one of the most recent update to either 830 or 840. The status bar icons worked before as well, until 840. The quick settings transparency and blur last worked on 802, and have not worked for me since 810. 

I'm not sure if this is something that works for other people and I'm the only one with a weird issue or what. but I very much miss when these features worked.

All of the other features that I use OOS customizer for work, so I know the module is working to some capacity.

Let me know if I can provide anything to help diagnose.

### Steps to reproduce

1. Try to change settings for the associated features using the app
2. Restart systemUI or entire device
3. Settings do not take any effect/ make any changes

### Expected behavior

Expected behavior: 
1) switching notification style actually changes notification style
2) selecting a Signal and Wifi Icon style actually themes the icons
3) changing quick settings blur and transparency level changes the background 

### Screenshots

No screenshots really; the settings just don't function. 

### Device information

- Device: OnePlus 12
- OS: CPH2583_14.0.0.840 (EX01)
- App version: "nightly-10 (#842) but has been at least 150 builds of non functionality on these features

**Comment by DHD2280** [comment]
For me everything is working, I'm on OnePlus 11 14.0.0.831.
Which root method are you using?
For Magisk:
Remove module and reboot so the module will be flashed again.
For KSU: disable unmount modules.

**Comment by nanodan52** [comment]
> For me everything is working, I'm on OnePlus 11 14.0.0.831. Which root method are you using? For Magisk: Remove module and reboot so the module will be flashed again. For KSU: disable unmount modules.

I am using KSU. 
I deleted the Oxygen Customizer module and rebooted.
In Oxygen Customizer, reinstalled the overlays and rebooted.
I tried to change one of the settings described as nonfunctioning in this issue, and no change was observed. They are still not working.

Things that don't work:
1) changing notification style makes no effect
2) quick settings transparency and window level blur makes no effect
3) changing status bar icon style (wifi, signal) makes no effect
4) changing toast style observes the added accent, however the main dialog color does not change

Things that affect SystemUI that I have tried that work:
1) I can change battery icon style
2) I can recolor quick settings tiles and volume/brightness slider
3) I can resize and recolor the status bar clock, and add padding if necessary
4) I can add weather information to the lock screen.

**Comment by DHD2280** [comment]
> I am using KSU.

Disabled unmount modules?

> Things that don't work:
> 
> 1. changing notification style makes no effect
> 2. quick settings transparency and window level blur makes no effect
> 3. changing status bar icon style (wifi, signal) makes no effect
> 4. changing toast style observes the added accent, however the main dialog color does not change

1) try to disable unmount modules in ksu.
Try to install overlayfs module by

2) bugged since August security patch, probably will remove.

3) same as 1.
4) the toast stile background should look like the preview in the app.

Edit:
Also try this command as root
`cmd overlay list | grep SGIC`
And paste output

**Comment by nanodan52** [comment]
> > I am using KSU.
> 
> Disabled unmount modules?
> 
> > Things that don't work:
> > 
> > 1. changing notification style makes no effect
> > 2. quick settings transparency and window level blur makes no effect
> > 3. changing status bar icon style (wifi, signal) makes no effect
> > 4. changing toast style observes the added accent, however the main dialog color does not change
> 
> 1. try to disable unmount modules in ksu.
>    Try to install overlayfs module by
> 2. bugged since August security patch, probably will remove.
> 3. same as 1.
> 4. the toast stile background should look like the preview in the app.
> 
> Edit: Also try this command as root `cmd overlay list | grep SGIC` And paste output

Ah, disable default umount modules. That seemed to work. 

Notification theming and status bar icon theming seems to be working now. Thank you for the support and amazing application. 

By the way, is it possible to theme the media notification background too? For example, the now playing notification from Spotify. It is still the ugly grey oneplus uses while all the other notifications are black (as they should be).

Thanks again! 

Edit: for what it's worth, I really liked the QS panel transparency and blur feature. I don't know what it would take to fix it, but I hope you don't decide to drop it permanently. Cheers :)
