### ISSUE TITLE
[BUG] Overlays are not created

### ISSUE THREAD

**Issue by Shukurjon28** [DHD2280/Oxygen-Customizer#82]
### Describe the bug

I launch the program, give all permissions, the process of creating overlays is in progress, but then after rebooting everything starts over again, as if the program data was cleared... and there are no overlays. When I launch it again, everything starts over again.
Beta version is working excellent, but new 2.0.0 version can't work 

### Steps to reproduce

1. Start app
2. Give all permissions
3. App making overlays 
4. Reboot device 
5. Lauch app
6. We see that there are no overlays and it asks to create them again.
7. And so on in a circle

### Expected behavior

Fix it

### Device information

- Device: Realme 10 4G
- OS: RealmeUI 5.0 (based on ColorOS and OxygenOS)
- App version: 2.0.0

**Comment by DHD2280** [comment]
Hello.
If the beta is working fine, then the stable should work same.
Without any logs/other informations I can't help you.
KSU/Magisk/Apatch?
Disabled unmount modules if using KSU?
Updated KSU/Apatch?

**Comment by Shukurjon28** [comment]
I found a way to use the program. After creating overlays, if you don't reboot, you can go into the program and customize everything (all functionality works). I have kernelSU installed, unmounting is disabled. KSU latest version.

**Comment by Shukurjon28** [comment]
I was able to install the app!!! Everything works. We can assume that there was no bug since I forgot to grant root rights to SystemUI. Everything works now.
