### ISSUE TITLE
[FEATURE] add ColorOS support (it based on OxygenOS)

### ISSUE THREAD

**Issue by Shukurjon28** [DHD2280/Oxygen-Customizer#83]
### Describe the feature

Add ColorOS support for oxygen customizer 

### Why would it be useful to add?

Developing the app and increasing the fan base

### Example(s)

...

**Comment by DHD2280** [comment]
Hello.
I know that OxygenOS is based on ColorOS.
Users reported working on ColorOS too.
If you find any just open issue with a more concise description about the issue.
