### ISSUE TITLE
Battery icon question

### ISSUE THREAD

**Issue by Suni-code** [DHD2280/Oxygen-Customizer#92]
### Describe the bug

Dear developer
When in the desktop slide control center, the battery icon will be incorrectly displayed in dark color.

### Steps to reproduce

1. Go to desktop
2. Scroll down to control center

### Expected behavior

Fix this problem

### Screenshots

![IMG_20241128_123811](https://github.com/user-attachments/assets/d34e5acb-9304-4467-94dd-0574982536d0)

### Device information

- Device: [e.g. OnePlus 9 Pro]
- OS: [e.g. Coloros OS 14 with update 14.0.0.720]
- App version: [e.g. v2.0.1]

**Comment by DHD2280** [comment]
Which battery style?
Lsposed version?
Enable more logs in settings and send lsposed logs.
This issue was fixed a long time ago.
I can't reproduce anymore.

**Comment by Suni-code** [comment]
@DHD2280
The battery style is iOS16.
Lsposed The version is 1.9.2 (7058)

**Comment by DHD2280** [comment]
> @DHD2280
> The battery style is iOS16.
> Lsposed The version is 1.9.2 (7058)

Try with battery style Landscape L

**Comment by Suni-code** [comment]
@DHD2280 
It's normal after switching
Can the battery style of iOS16 be repaired?😭
I like that bold text.

**Comment by DHD2280** [comment]
> @DHD2280 
> It's normal after switching
> Can the battery style of iOS16 be repaired?😭
> I like that bold text.

Hello.
Any news?
The battery icon was improved a bit and should be better now.
Please let me know

**Comment by Suni-code** [comment]
> > @DHD2280 
> > It's normal after switching
> > Can the battery style of iOS16 be repaired?😭
> > I like that bold text.
> 
> Hello.
> Any news?
> The battery icon was improved a bit and should be better now.
> Please let me know

![Screenshot_2024-12-05-18-23-51-11_b783bf344239542886fee7b48fa4b892.jpg](https://github.com/user-attachments/assets/8114b372-4523-40be-9ed3-56140097bee3)

It's normal now👍🏻
